version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

  backend:
    build:
      context: pharmacy-back
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: pharmacy-app
      dockerfile: Dockerfile.frontend
      args:
        REACT_APP_BACKEND_URL: "http://backend:5000"
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
