version: '3.8'

services:
  backend:
    build:
      context: pharmacy-back
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build:
      context: pharmacy-app
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env